version: "3.9"
services:
    bits-stack-backend:
        container_name: bits-stack-backend
        image: bits-stack-backend
        restart: always
        command: npm start
        build: .
        ports:
          - "5000:5000"
        volumes:
          - ./:/usr/src/app/
          - /usr/src/app/node_modules