version: "3.9"
services:
    bits-stack-backend:
        container_name: bits-stack-backend
        image: bits-stack-backend
        restart: always
        command: npm start
        build: .
        ports:
          - "5000:5000"
        volumes:
          - ./:/usr/src/app/
          - /usr/src/app/node_modules
        depends_on:
          - postgres
    postgres:
        container_name: postgres
        image: postgres:12
        networks:
          - webnet
        environment:
          POSTGRES_PASSWORD: eatsleepcode
          POSTGRES_USER: postgres
          POSTGRES_DB: bitstack
          PG_DATA: /var/lib/postgresql/data
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data    
networks:
  webnet:       
volumes:
  pgdata:      