version: "3.9"
services:
  bits-stack-backend:
    container_name: bits-stack-backend
    #image: bits-stack-backend
    #restart: always
    command: npm run docker:dev
    build: .
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - webnet
    depends_on:
      - postgres
    working_dir: /usr/src/app
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      #here variable are used to createdefault DB for bitstack
      POSTGRES_PASSWORD: eatsleepcode
      POSTGRES_USER: postgres
      POSTGRES_DB: bitstack
      # here it'll keep al psql data of bitstack
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:6.2
    networks:
      - webnet
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
networks:
  webnet:
volumes:
  pgdata:
